```plantuml
@startuml
component "소셜 API" as SocialAPI
component "회원가입" as Registration
component "로그인" as Login
component "계정 관리" as AccountManagement
component "킥보드/자전거 조회" as VehicleSearch
component "대여" as Rental
component "반납" as Return
component "결제 API" as PaymentAPI
component "지도 API" as MapAPI

SocialAPI --> Registration
Registration --> Login
Login --> AccountManagement
Login --> VehicleSearch
VehicleSearch --> MapAPI
VehicleSearch --> Rental
Rental --> Return
Return --> PaymentAPI
@enduml