@startuml

package "External API" {
   component "소셜 API" as SocialAPI
   component "결제 API" as PaymentAPI
   component "지도 API" as MapAPI
}

package "Internal Components" {
   package "계정 관리" as AccountManagement {
      component "회원가입 API" as RegisterAPI
   }

   package "서비스 관리" as ServiceManagement {
      component "결제 API" as PaymentIntegration
      component "지도 API" as MapIntegration
   }
}

RegisterAPI ..> SocialAPI : OAuth 인증

PaymentIntegration ..> PaymentAPI : 결제 요청/응답
MapIntegration ..> MapAPI : 위치 정보 요청

@enduml
